# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tmgr"
dynamic = ["version"] 


classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: System :: Distributed Computing",
    "Operating System :: OS Independent"
]

dependencies = [
    "SQLAlchemy>=2.0.0",
    "python-dotenv",
    "psycopg-pool",
    "psycopg[binary]"
]

requires-python = ">=3.7"